name: Validate credentials
description: Action for validate credentials for GitHub, Telegram
inputs:
  github_token:
    description: Token for GitHub account
    required: false
  telegram_token:
    description: Token for Telegram Bot
    required: false
  telegram_chat_id:
    description: ID of validating Telegram Chat
    required: false

branding:
  icon: 'message-square'
  color: 'blue'
runs:
  using: docker
  image: docker://ghcr.io/ci-space/validate-credentials:v0.1.0
